/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SHA3 */

#ifndef _Included_SHA3
#define _Included_SHA3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SHA3
 * Method:    initialise
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_SHA3_initialise
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     SHA3
 * Method:    update
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_SHA3_update
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     SHA3
 * Method:    digest
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_SHA3_digest
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
